permissions:
  admin: playerrooms.admin
  force-join: playerrooms.forcejoin
rooms:
  room1:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.player
      make-private: playerrooms.player
  room2:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.player
      make-private: playerrooms.player
  room3:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.player
      make-private: playerrooms.player
  room4:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.player
      make-private: playerrooms.player
  room5:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.player
      make-private: playerrooms.player
  room6:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.player
      make-private: playerrooms.player
  room7:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.player
      make-private: playerrooms.player
  room8:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.player
      make-private: playerrooms.player
  room9:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.player
      make-private: playerrooms.player
  room10:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.1
      make-private: playerrooms.donate.vip.1
  room11:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.1
      make-private: playerrooms.donate.vip.1
  room12:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.1
      make-private: playerrooms.donate.vip.1
  room13:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.1
      make-private: playerrooms.donate.vip.1
  room14:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.1
      make-private: playerrooms.donate.vip.1
  room15:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.1
      make-private: playerrooms.donate.vip.1
  room16:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.1
      make-private: playerrooms.donate.vip.1
  room17:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.1
      make-private: playerrooms.donate.vip.1
  room18:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.1
      make-private: playerrooms.donate.vip.1
  room19:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.2
      make-private: playerrooms.donate.vip.2
  room20:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.2
      make-private: playerrooms.donate.vip.2
  room21:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.2
      make-private: playerrooms.donate.vip.2
  room22:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.2
      make-private: playerrooms.donate.vip.2
  room23:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.2
      make-private: playerrooms.donate.vip.2
  room24:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.2
      make-private: playerrooms.donate.vip.2
  room25:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.2
      make-private: playerrooms.donate.vip.2
  room26:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.2
      make-private: playerrooms.donate.vip.2
  room27:
    spawn-point: 0 90 0
    min: -10 85 -10
    max: 10 100 10
    max-players-default: 4
    permissions:
      join: playerrooms.donate.vip.2
      make-private: playerrooms.donate.vip.2

gui:
  strings:
    private-state:
      open:
        text: "Открыта" # %private_text%
        color: "#00FF00" # %private_color%
      private:
        text: "Закрыта" # %private_text%
        color: "#FF0000" # %private_color%
    busy-state:
      free:
        text: "Свободна" # %busy_text%
        color: "#00FF00" # %busy_color%
      busy:
        text: "Занята" # %busy_text%
        color: "#FF0000" # %busy_color%

  pages:
    1:
      name: "#FF0000PlayerRooms"
      size: 54
      slots:
        0:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        1:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        2:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        3:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        4:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        5:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        6:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        7:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        8:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        9:
          name: "%busy_color%Обычная комната"
          material: BOOKSHELF
          linked-room: room1
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        10:
          name: "%busy_color%Обычная комната"
          material: BOOKSHELF
          linked-room: room2
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        11:
          name: "%busy_color%Обычная комната"
          material: BOOKSHELF
          linked-room: room3
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        12:
          name: "%busy_color%Обычная комната"
          material: BOOKSHELF
          linked-room: room4
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        13:
          name: "%busy_color%Обычная комната"
          material: BOOKSHELF
          linked-room: room5
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        14:
          name: "%busy_color%Обычная комната"
          material: BOOKSHELF
          linked-room: room6
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        15:
          name: "%busy_color%Обычная комната"
          material: BOOKSHELF
          linked-room: room7
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        16:
          name: "%busy_color%Обычная комната"
          material: BOOKSHELF
          linked-room: room8
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        17:
          name: "%busy_color%Обычная комната"
          material: BOOKSHELF
          linked-room: room9
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        18:
          name: "%busy_color%VIP комната: Улей"
          material: HONEYCOMB_BLOCK
          linked-room: room10
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        19:
          name: "%busy_color%VIP комната: Улей"
          material: HONEYCOMB_BLOCK
          linked-room: room11
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        20:
          name: "%busy_color%VIP комната: Улей"
          material: HONEYCOMB_BLOCK
          linked-room: room12
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        21:
          name: "%busy_color%VIP комната: Улей"
          material: HONEYCOMB_BLOCK
          linked-room: room13
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        22:
          name: "%busy_color%VIP комната: Улей"
          material: HONEYCOMB_BLOCK
          linked-room: room14
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        23:
          name: "%busy_color%VIP комната: Улей"
          material: HONEYCOMB_BLOCK
          linked-room: room15
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        24:
          name: "%busy_color%VIP комната: Улей"
          material: HONEYCOMB_BLOCK
          linked-room: room16
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        25:
          name: "%busy_color%VIP комната: Улей"
          material: HONEYCOMB_BLOCK
          linked-room: room17
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        26:
          name: "%busy_color%VIP комната: Улей"
          material: HONEYCOMB_BLOCK
          linked-room: room18
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        27:
          name: "%busy_color%VIP комната: Остров"
          material: GRASS_BLOCK
          linked-room: room19
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        28:
          name: "%busy_color%VIP комната: Остров"
          material: GRASS_BLOCK
          linked-room: room20
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        29:
          name: "%busy_color%VIP комната: Остров"
          material: GRASS_BLOCK
          linked-room: room24
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        30:
          name: "%busy_color%VIP комната: Остров"
          material: GRASS_BLOCK
          linked-room: room22
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        31:
          name: "%busy_color%VIP комната: Остров"
          material: GRASS_BLOCK
          linked-room: room23
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        32:
          name: "%busy_color%VIP комната: Остров"
          material: GRASS_BLOCK
          linked-room: room24
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        33:
          name: "%busy_color%VIP комната: Остров"
          material: GRASS_BLOCK
          linked-room: room25
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        34:
          name: "%busy_color%VIP комната: Остров"
          material: GRASS_BLOCK
          linked-room: room26
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        35:
          name: "%busy_color%VIP комната: Остров"
          material: GRASS_BLOCK
          linked-room: room27
          lore:
            - "%busy_color%Места: %current_player%/%max_players%"
            - "%private_color%%busy_color%Комната %private_text%"
        36:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        37:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        38:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        39:
          name: "Previous page"
          material: ARROW
          action: previous-page
        40:
          name: ""
          material: SPECTRAL_ARROW
        41:
          name: "Next page"
          material: ARROW
          action: next-page
        42:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        43:
          name: ""
          material: GRAY_STAINED_GLASS_PANE
        44:
          name: ""
          material: GRAY_STAINED_GLASS_PANE